---

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'db/migrate/**'
    - 'db/seeds.rb'

Style/Documentation:
  Enabled: false
Naming/VariableNumber:
  CheckSymbols: false
RSpec/MultipleExpectations:
  Max: 7
RSpec/ExampleLength:
  Max: 12
RSpec/Rails/InferredSpecType:
  Enabled: false
