default: &default
  adapter: sqlite3
  # adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  # database: gym_bot_dev

test:
  <<: *default
  database: db/test.sqlite3
  # database: gym_bot_test

production:
  <<: *default
  adapter: postgresql
  database: gym_bot_data